function [fitresult, gof] = createFit(lambdaplot, cor)
%CREATEFIT(LAMBDAPLOT,COR)
%  Create a fit.
%
%  Data for 'GaussianPixelFit' fit:
%      X Input : lambdaplot
%      Y Output: cor
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 14-Jun-2016 15:09:59


%% Fit: 'GaussianPixelFit'.
[xData, yData] = prepareCurveData( lambdaplot, cor );

% Set up fittype and options.
ft = fittype( 'gauss4' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0];
opts.StartPoint = [10979 587.6 0.393765175630334 494 582.727118644068 2.24331457888839 483.952237600095 577.472881355932 3.41865803511592 467.999955600962 591.837288135593 1.57649328895353];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'GaussianPixelFit' );
h = plot( fitresult, xData, yData );
% Label axes
ax = gca;
ax.FontSize = 15;
title('Counts vs wavelength (nm)','FontSize',15);
xlabel('Wavelength (nm)','FontSize',15);
ylabel('Counts','FontSize',15);
grid on;
end

